spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
    cache: false
    template_update_delay: 0
server:
  use-forward-headers: true
  tomcat:
    uri-encoding: UTF-8
    protocol_header: x-forwarded-proto
#开发环境
---
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALqXe1ncw3rJujiPlLZOrs4NawCca77oAl9y3A5OtAN9InIGPO1+PuEOu1LlSlVNlVIg5UHvWGAaWg1ZUwmZxtcCAwEAAQ==
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: UKQ9ohlOw0VDS4Br0eSuMpohUZt3h+8tujfL+KCyc5UFYFRr1dMquRDCdrWyVQb2ERTUhOdtbHFaqczRYolI2A==
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 2
      minIdle: 10
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: true
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      web-stat-filter:
        session-stat-enable: flase
      filter:
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${public-key}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 20000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-idle: 100
        max-wait: -1
        min-idle: 5
mybatis:
  type-aliases-package: com.study.xl.tymh.entity
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 8080
  servlet:
    context-path: "/"

