package com.study.xl.tymh.dao;

import com.study.xl.tymh.entity.Resource;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Aug 07 13:59:42 CST 2019
     */
    int updateByPrimaryKey(Resource record);

    List<Resource> listByUserId(Integer userId);

    List<Resource> listByRoleIdList(@Param("roleIdList") List<Integer> roleIdList);
}